### ISSUE TITLE
Provide an example, how to remap default key bindings

### ISSUE THREAD

**Issue by mrded** [irrationalistic/vim-tasks#2]
Hi, thank you for such great plugin, very handy!

Can you please Provide an example, how to remap default key bindings?

Unfortunately current bindings are conflicting with many popular modules like NERDTree.

Thank you.

**Comment by irrationalistic** [comment]
Thank you!

You should be able to override the global variables by just redefining them in your own vimrc:

```
let g:TasksMarkerBase = '[ ]'
let g:TasksMarkerDone = '[x]'
let g:TasksMarkerCancelled = '[-]'
let g:TasksMarkerBase = '-'
let g:TasksMarkerDone = '-'
let g:TasksMarkerCancelled = '-'
let g:TasksDateFormat = '%Y'
let g:TasksArchiveSeparator = '-----'
let g:TasksAttributeMarker = '#'
```

You can override any or all of them!

**Comment by mrded** [comment]
How can I override these?
* `<leader> n` - new task below
* `<leader> N` - new task above
* `<leader> d` - toggle current task complete
* `<leader> x` - toggle current task cancelled
* `<leader> a` - send completed tasks to the archive

**Comment by irrationalistic** [comment]
Ah! Sorry :)

I'm actually not quite certain what the "right" way to do this is, but you could just follow the format in https://github.com/irrationalistic/vim-tasks/blob/master/ftplugin/tasks.vim#L14 (minus the "buffer" bit) and set your own new bindings. Does that help?

**Comment by mrded** [comment]
Yes, it helped indeed! Thank you :)

I still think you should mention it in the README.md it's very useful to know.
